### ISSUE TITLE
vectored environments

### ISSUE THREAD

**Issue by raymondchua** [deepmind/dqn_zoo#16]
Hi,
Does this work with vectorized environments (such as using gym.vector.AsyncVectorEnv function)?

Best,
Raymond

**Comment by jqdm** [comment]
Not out of the box since DQN and variants expect a single stream of experience. One could get something working reasonably quickly by adapting `TransitionAccumulator` so it accepts a batch of time steps.

**Comment by raymondchua** [comment]
Awesome, thanks @jqdm !
