### ISSUE TITLE
How did you pick hyperparameter for the final run?

### ISSUE THREAD

**Issue by hmishfaq** [deepmind/dqn_zoo#20]
Do you choose the hyperparameters based of the different seeds from the ones you use for evaluation? I just want to understand how the hyperparameters were chosen and after choosing the hyperparameter if the algorithms were rerun.

**Comment by GeorgOstrovski** [comment]
dqn_zoo attempts to provide exact reproductions of previously published DQN-based algorithms - all hyperparameters in this repository were chosen to match those in the respective publications, and we did not perform any of our own tuning. 

If your question is about the original publications - the answer likely varies, and you'd have to go back to those papers to get details on how hyperparameter tuning was performed in each case.
