### ISSUE TITLE
Specifying CSV Write Path Creates FileNotFoundError

### ISSUE THREAD

**Issue by RylanSchaeffer** [deepmind/dqn_zoo#6]
When I specify the `--results_csv_path="/tmp/dqn_zoo/c51/pong/1/results.csv"`, I receive an error:

`[Errno 2] No such file or directory: '/tmp/dqn_zoo/c51/pong/1/results.csv'`

My suspicion is that nothing creates the necessary directories `/tmp/`, `/tmp/dqn_zoo/`, etc.

**Comment by jqdm** [comment]
Thanks for reporting, `CsvWriter` will create intermediate directories now, see eab9679b06f4f7d1b017a31197b7b4869003e7d5.
